### ISSUE TITLE
Chat.hs compilation failure

### ISSUE THREAD

**Issue by dserban** [ocharles/engine.io#26] opened 2015-08-11 00:16 UTC
```
Chat.hs:67:3:
    Couldn't match type `NewMessage -> m1 ()'
                  with `SocketIO.EventHandler a0'
    When using functional dependencies to combine
      Network.SocketIO.OnArgs a a,
        arising from the dependency `a -> r'
        in the instance declaration in `Network.SocketIO'
      Network.SocketIO.OnArgs
        (NewMessage -> m1 ()) (SocketIO.EventHandler a0),
        arising from a use of `SocketIO.on' at Chat.hs:67:3-13
    In the expression: SocketIO.on "new message"
    In a stmt of a 'do' block:
      SocketIO.on "new message"
      $ \ (NewMessage message)
          -> forUserName
             $ \ userName
                 -> SocketIO.broadcast "new message" (Said userName message)

Chat.hs:71:3:
    Couldn't match type `AddUser -> m2 ()'
                  with `SocketIO.EventHandler a1'
    When using functional dependencies to combine
      Network.SocketIO.OnArgs a a,
        arising from the dependency `a -> r'
        in the instance declaration in `Network.SocketIO'
      Network.SocketIO.OnArgs
        (AddUser -> m2 ()) (SocketIO.EventHandler a1),
        arising from a use of `SocketIO.on' at Chat.hs:71:3-13
    In the expression: SocketIO.on "add user"
    In a stmt of a 'do' block:
      SocketIO.on "add user"
      $ \ (AddUser userName)
          -> do { n <- liftIO $ STM.atomically $ do { ... };
                  SocketIO.emit "login" (NumConnected n);
                  .... }
```

My version of `cabal`:

```
$ cabal -V
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library 
```

**Comment by ocharles** [comment] 2015-08-20 08:51
I'm unable to reproduce this on GHC 7.10. Are you perhaps on an older version of GHC?

**Comment by dserban** [comment] 2015-08-20 11:19
Yes, 7.6.3 since I'm on Ubuntu 14.04.
Oh well.
Closing the ticket now.

**Comment by ocharles** [comment] 2015-08-20 11:24
No need to close, I just need to know where to reproduce the bug :) I'll see if I can convince it to infer on those older compilers.

**Comment by ocharles** [comment] 2017-02-07 11:22
GHC 7.6 is too old for this project, I won't be fixing this. If anyone submits a PR to get things working on 7.6, I will consider merging it (provided it doesn't require too much to change).

**Closed by ocharles** 2017-02-07 11:22 UTC
